name: todo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.16.0-nullsafety.0 <2.0.0"
  hooks_riverpod: ^2.4.0
  riverpod: ^2.4.0
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true